config:
  futures_a:
    data:
    - tick
    - trade_info
    session:
    - am_1
    - pm_1
  futures_b:
    data:
    - tick
    - trade_info
    session:
    - am_1
  index:
    data:
    - tick
    session:
    - am_2
  option:
    data:
    - tick
    - trade_info
    session:
    - am_1
    - pm_1
  stock:
    data:
    - tick
    session:
    - am_2
session_time:
  am_1: 0845-1345
  am_2: 0900-1330
  pm_1: 1500-0500
symbol:
  futures_a:
  - TX00
  - MTX00
  - UDF00
  futures_b:
  - TE00
  - TF00
  - HBF00
  - JZF00
  - LXF00
  - KKF00
  - IMF00
  - CXF00
  - JBF00
  - DHF00
  - DUF00
  - NOF00
  - CDF00
  - HCF00
  - CHF00
  - FTF00
  - GXF00
  - NAF00
  - CSF00
  - FYF00
  - FZF00
  - OLF00
  - DSF00
  - DVF00
  - MCF00
  - MKF00
  - DQF00
  - GUF00
  - FFF00
  - DOF00
  - NIF00
  - GIF00
  - CZF00
  - GJF00
  - NVF00
  - LIF00
  - OWF00
  - JNF00
  - LUF00
  - CYF00
  - NTF00
  - CCF00
  - CUF00
  - OVF00
  - OPF00
  - DFF00
  - GWF00
  - MAF00
  index:
  - TSEA
  - TSE13
  - TSE17
  - TWXI
  - OTCA
  option:
  stock:
  - 2330
  - 2317
  - 6505
  - 2412
  - 2882
  - 3008
  - 2327
  - 00677U
